name: scikit-learn-course

channels:
  - conda-forge

dependencies:
  - scikit-learn >= 1.1.1
  - pandas >= 1
  - matplotlib-base
  - seaborn
  - jupyterlab
  - notebook
  - jupytext
  - plotly
  - ptitprince
  - IPython
