name: scikit-learn-course
channels:
  - conda-forge
dependencies:
  - python=3.11
  - scikit-learn >= 1.8
  - pandas >= 1
  - matplotlib-base
  - seaborn >= 0.13
  - plotly >= 5.10
  - jupytext
  - beautifulsoup4
  - IPython
  - packaging
  - pip
  - pip:
    - jupyter-book < 2.0
