name: scikit-learn-course
channels:
  - conda-forge
dependencies:
  - scikit-learn >= 0.24
  - imbalanced-learn
  - pandas >= 1
  - matplotlib-base
  - seaborn
  - plotly
  - jupytext
  - beautifulsoup4
  - pip
  - pip:
    - jupyter-book >= 0.11
