name: scikit-learn-tutorial

channels:
  - conda-forge

dependencies:
  - scikit-learn >= 0.23.2
  - pandas >= 1
  - pandas-profiling >= 2.5
  - matplotlib-base
  - seaborn
  - jupyterlab
  - notebook
  - jupytext
  - plotly
  # pin nbconvert to avoid adding execution_count field
  # on markdown cells when generating rendered_notebooks/
  # otherwise we get a warning when opening the file in
  # jupyter notebook (6.1.4 at this time).
  - nbconvert = 5.6.1
