version: 2

jobs:
  build_jupyter_book:
    docker:
      - image: continuumio/miniconda
    environment:
      - OMP_NUM_THREADS: 2
      - MKL_NUM_THREADS: 2
      - OPENBLAS_NUM_THREADS: 2
      - MINICONDA_PATH: ~/miniconda
      - CONDA_ENV_NAME: testenv
      - PYTHON_VERSION: 3
    steps:
      - checkout
      - run: ./build_tools/circle/checkout_merge_commit.sh
      - run:
          command: ./build_tools/circle/build_jupyter_book.sh
          no_output_timeout: 30m
      - store_artifacts:
          path: jupyter-book/_build/html
          destination: notebooks

workflows:
  version: 2
  build_jupyter_book:
    jobs:
      # TODO add lint step
      # - lint
      - build_jupyter_book
          # requires:
          #   - lint
