version: 2

jobs:
  build_jupyter_book:
    docker:
      - image: continuumio/miniconda
    environment:
      - OMP_NUM_THREADS: 1
      - MKL_NUM_THREADS: 2
      - OPENBLAS_NUM_THREADS: 2
      - MINICONDA_PATH: ~/miniconda
    steps:
      - checkout
      - run: ./build_tools/circle/checkout_merge_commit.sh
      - run: ./build_tools/circle/checksum_python_files.sh /tmp/checksum.txt
      # - restore_cache:
      #     keys:
      #       - v3-{{ .Branch }}-{{ checksum "/tmp/checksum.txt" }}
      #       - v3-{{ .Branch }}
      #       - v3-main
      - run:
          command: ./build_tools/circle/build_jupyter_book.sh
          no_output_timeout: 30m
      # - save_cache:
      #     paths:
      #       - jupyter-book/_build/.jupyter_cache
      #     key: v3-{{ .Branch }}-{{ checksum "/tmp/checksum.txt" }}
      - store_artifacts:
          path: jupyter-book/_build/html
          destination: jupyter-book

workflows:
  version: 2
  build_jupyter_book:
    jobs:
      # TODO add lint step
      # - lint
      - build_jupyter_book
          # requires:
          #   - lint
