name: scikit-learn-tutorial

channels:
  - conda-forge

dependencies:
  - python=3.8
  - scikit-learn >= 0.23.2
  - pandas >= 1
  - pandas-profiling >= 2.5
  - matplotlib-base
  - seaborn
  - jupyterlab
  - notebook
  - jupytext
  - plotly
