name: scikit-learn-course

channels:
  - conda-forge

dependencies:
  - python=3.8
  - scikit-learn >= 0.23.2
  - pandas >= 1
  - matplotlib-base
  - seaborn
  - jupyterlab
  - notebook
  - jupytext
  - plotly
